services:
  nginx:
    depends_on:
      - front-end
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80

  front-end:
    image: ghcr.io/mcmastercce/bvd-103-mcmasterful-books/mcmasterful-books-docker:main
    volumes:
      - ./adapter:/source/adapter

  books:
    build:
      context: ./src/books
      dockerfile: Dockerfile
    depends_on:
      - mongo-books
      - rabbitmq
    environment:
      - MONGO_URI=mongodb://mongo-books
      - AMQP_URL=amqp://rabbitmq:5672
      - PORT=3000
    ports:
      - 3000:3000
    # command: sh -c "while true; do sleep 1000; done"

  mongo-books:
    image: mongo:latest
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:management-alpine
